# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/configuration-reference
version: 2.1

orbs:
  android: circleci/android@2.5.0
# Define a job to be invoked later in a workflow.
# See: https://circleci.com/docs/jobs-steps/#jobs-overview & https://circleci.com/docs/configuration-reference/#jobs
jobs:
  
    run-unit-test:
      executor:
        name: android/android-docker
        tag: 2024.08
      steps:
        - checkout
        - android/restore-gradle-cache
        - android/run-tests:
          test-command: ./gradlew testDebugUnitTest
        - android/save-gradle-cache


# Orchestrate jobs using workflows
# See: https://circleci.com/docs/workflows/ & https://circleci.com/docs/configuration-reference/#workflows
workflows:
  build-and-test:
    jobs:
        - run-unit-test